id: P005408
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18572
  title: རྒྱལ་དར་དང་། རྒྱལ་རྟགས། རྒྱལ་གླུ་བཅས་ཀྱི་སྐོར་གླེང་བ།
  author: ''
  volumes:
    c1a311b6922e4c0f8ef8789d60a7c86d:
      image_group_id: I1KG18663
      title: ''
      volume_number: 1
      total_pages: 174
