id: IDA8AA8BF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:09:39+00:00'
last_modified: '2022-06-08T02:52:22.220610+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18572
  title: རྒྱལ་དར་དང་། རྒྱལ་རྟགས། རྒྱལ་གླུ་བཅས་ཀྱི་སྐོར་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A6BF:
      image_group_id: I1KG18663
      title: ''
      total_pages: 174
      order: 1
      base_file: A6BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
